#!/usr/bin/env bash

# Original script by @speltriao on GitHub
# https://github.com/speltriao/Pacman-Update-for-GNOME-Shell

# If the operating system is not Arch Linux, exit the script successfully
if [ ! -f /etc/arch-release ]; then
    exit 0
fi

if command -v paru >/dev/null 2>&1; then
    AUR_HELPER=paru
elif command -v yay >/dev/null 2>&1; then
    AUR_HELPER=yay
fi

if [ -n "$AUR_HELPER" ]; then
    AUR=$("$AUR_HELPER" -Qua | wc -l)
    ALL=$("$AUR_HELPER" -Qet | wc -l)
else
    AUR=0
    ALL=$(pacman -Qet | wc -l)
fi
OFFICIAL=$(checkupdates | wc -l)

# Case/switch for each service updates
case $1 in
    aur) echo " $AUR";;
    official) echo " $OFFICIAL";;
esac

# If the parameter is "update", update all services
if [ "$1" = "update" ]; then
    if [ -n "$AUR_HELPER" ]; then
        kitty "$AUR_HELPER" -Syu
    else
        kitty sudo pacman -Syu
    fi
    pkill -SIGRTMIN+8 waybar
fi

# If there aren't any parameters, return the total number of updates
if [ "$1" = "" ]; then
    COUNT=$((OFFICIAL+AUR))

    if [[ "$COUNT" = "0" ]]
    then
        printf '{"text": "%s", "tooltip": "%s"}\n' " $ALL" " $ALL "
    else
        printf '{"text": "%s", "tooltip": "%s"}\n' " $COUNT" " $COUNT of  $ALL"
    fi
    exit 0
fi
